/** Semantic CSS custom properties — applied to `document.documentElement` by ThemeProvider */
export const lightThemeVars: Record<string, string> = {
  '--md-page': '#f5f5f5',
  '--md-text': '#111827',
  '--md-text-muted': '#6b7280',
  '--md-text-subtle': '#374151',
  '--md-surface': '#ffffff',
  '--md-surface-muted': '#f9fafb',
  '--md-surface-card': '#fafafa',
  '--md-border': '#e5e7eb',
  '--md-border-strong': '#d1d5db',
  '--md-primary': '#1e3a8a',
  '--md-on-primary': '#ffffff',
  '--md-positive': '#16a34a',
  '--md-negative': '#dc2626',
  '--md-error-bg': '#fee2e2',
  '--md-chart-surface': '#f0fff0',
  '--md-chart-border': '#90ee90',
  '--md-accent-blue-bg': '#e0f6ff',
  '--md-accent-blue-border': '#87ceeb',
  '--md-accent-green-bg': '#f0fff0',
  '--md-accent-green-border': '#90ee90',
  '--md-warning-bg': '#fffbeb',
  '--md-warning-border': '#f59e0b',
  '--md-warning-text': '#92400e',
  '--md-info-icon-border': '#9ca3af',
  '--md-info-icon-fg': '#4b5563',
  '--md-pos-muted-bg': '#dcfce7',
  '--md-pos-muted-border': '#86efac',
  '--md-pos-text-strong': '#166534',
  '--md-neg-muted-bg': '#fee2e2',
  '--md-neg-muted-border': '#fca5a5',
  '--md-neg-text-strong': '#991b1b',
  '--md-neutral-chip-bg': '#f3f4f6',
  '--md-row-divider': '#f3f4f6',
  '--md-empty-text': '#666666',
  '--md-tab-border': '#d1d5db',
  '--md-shadow-tooltip': '0 2px 8px rgba(0,0,0,0.15)',
  '--md-chart-grid': '#e5e7eb',
  '--md-chart-axis': '#6b7280',
  '--md-chart-zero': '#111827',
  '--md-input-bg': '#ffffff',
}

export const darkThemeVars: Record<string, string> = {
  '--md-page': '#0f172a',
  '--md-text': '#f1f5f9',
  '--md-text-muted': '#94a3b8',
  '--md-text-subtle': '#cbd5e1',
  '--md-surface': '#1e293b',
  '--md-surface-muted': '#334155',
  '--md-surface-card': '#263449',
  '--md-border': '#475569',
  '--md-border-strong': '#64748b',
  '--md-primary': '#3b82f6',
  '--md-on-primary': '#ffffff',
  '--md-positive': '#4ade80',
  '--md-negative': '#f87171',
  '--md-error-bg': '#450a0a',
  '--md-chart-surface': '#0f2918',
  '--md-chart-border': '#15803d',
  '--md-accent-blue-bg': '#172554',
  '--md-accent-blue-border': '#3b82f6',
  '--md-accent-green-bg': '#0f2918',
  '--md-accent-green-border': '#22c55e',
  '--md-warning-bg': '#422006',
  '--md-warning-border': '#d97706',
  '--md-warning-text': '#fcd34d',
  '--md-info-icon-border': '#64748b',
  '--md-info-icon-fg': '#cbd5e1',
  '--md-pos-muted-bg': '#14532d',
  '--md-pos-muted-border': '#22c55e',
  '--md-pos-text-strong': '#bbf7d0',
  '--md-neg-muted-bg': '#450a0a',
  '--md-neg-muted-border': '#dc2626',
  '--md-neg-text-strong': '#fecaca',
  '--md-neutral-chip-bg': '#334155',
  '--md-row-divider': '#334155',
  '--md-empty-text': '#94a3b8',
  '--md-tab-border': '#475569',
  '--md-shadow-tooltip': '0 4px 20px rgba(0,0,0,0.45)',
  '--md-chart-grid': '#475569',
  '--md-chart-axis': '#94a3b8',
  '--md-chart-zero': '#e2e8f0',
  '--md-input-bg': '#0f172a',
}

export type MdTheme = 'light' | 'dark'

export function applyThemeToDocument(theme: MdTheme) {
  const vars = theme === 'dark' ? darkThemeVars : lightThemeVars
  const root = document.documentElement
  Object.entries(vars).forEach(([key, value]) => {
    root.style.setProperty(key, value)
  })
  root.setAttribute('data-theme', theme)
}
